api_version: 2
name: asr_fl_test
description: ASR sample project yaml file for federated Learning
participants:
# change example.com to the FQDN of the server
  - name: grace-central-1.grace-fct.eu
    type: server
    org: iti
    fed_learn_port: 18002
    admin_port: 18003
    # enable_byoc loads python codes in app. Default is false.
    enable_byoc: true
  - name: site-1
    type: client
    org: iti
    enable_byoc: true
  - name: site-2
    type: client
    org: iti
    enable_byoc: true
  - name: admin@grace.com
    type: admin
    org: iti
    roles:
      - super
# The same methods in all builders are called in their order defined in builders section
builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file: master_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      # config_folder can be set to inform NVFlare where to get configuration
      config_folder: config
      # when docker_image is set to a docker image name, docker.sh will be generated on server/client/admin
      # docker_image:
  - path: nvflare.lighter.impl.auth_policy.AuthPolicyBuilder
    args:
      orgs:
        iti:
          - relaxed
      roles:
        super: super user of system
      groups:
        relaxed:
          desc: org group with relaxed policies
          rules:
            allow_byoc: true
            allow_custom_datalist: true
      disabled: false
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.he.HEBuilder
    args:
      poly_modulus_degree: 8192
      coeff_mod_bit_sizes: [60, 40, 40]
      scale_bits: 40
      scheme: CKKS
  - path: nvflare.lighter.impl.signature.SignatureBuilder
  - path: nvflare.lighter.impl.workspace.DistributionBuilder
    args:
      zip_password: false
